MODEL:
  NAME: "inception_v3"
  PRETRAINED: "inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5"
DATASET:
  NAME: "midia_chinese_food"
  ROOT: "D:\\dataset\\midia_chinese_food\\release_data\\"
SOLVER:
  OUTPUT_DIR: "inception_v3_midia_chinese_food\\"
  LR:
    POLICY: "cosine"
    START: 1e-2
    FINAL: 1e-5
  WARMUP:
    START: 1e-8
    STEPS: 100

  EPOCH_TOTAL: 50
  BATCH_SIZE: 64
  FREEZE_BACKBONE: False
  CLIP_GRADIENT: -1

EVALUATION:
  MODEL_PATH: "model_save/50_0.371.ckpt"
  IMAGES: "D:\\dataset\\midia_chinese_food\\release_data\\test\\"
  OUTPUT_DIR: "inception_v3_midia_chinese_food\\evaluation\\"
  "MAX_NUM": 100
  "CLASS_NAMES": "D:\\dataset\\midia_chinese_food\\class_names.csv"
